blank_issues_enabled: false
contact_links:
  - name: Questions / discussions
    url: https://github.com/y-zahidi
    about: For general questions, please email yassirzahidi8@gmail.com or reach out on LinkedIn.
